# Generated by Django 6.0.7 on 2026-07-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Sports', 'Sports')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='vehicles',
            constraint=models.UniqueConstraint(fields=('make', 'model'), name='unique_make_model'),
        ),
    ]
